version: '2.2'
services:

  after-init:
    image: dimmsd/ubuntu-base:16.04
    command: /tmp/utils/after-init-php-fpm.sh
    environment:
      - PHP_FPM_LOG_PERMISSION=${PHP_FPM_LOG_PERMISSION}
    depends_on:
      - php-fpm
      - httpd
    volumes:
      - ./utils:/tmp/utils
      - ./log-fpm:/tmp/log-fpm
    networks:
      test_demo:

  httpd:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        COMMIT: ${COMMIT}
    image: ${HTTPD_IMAGE}:${UBUNTU_VERSION}
    container_name: con-${HTTPD_IMAGE}
    depends_on:
      - php-fpm
    links:
      - php-fpm
    environment:
      - MAIN_DOMAIN=${MAIN_DOMAIN}
      - MAIN_PATH=${MAIN_PATH}
      - TIMEZONE=${TIMEZONE}
      - CLEAR_APACHE_LOG=${CLEAR_APACHE_LOG}
    extra_hosts:
      - "${MAIN_DOMAIN}:127.0.0.1"
    volumes:
      - ./www:/var/www
      - ./apache/sites:/etc/apache2/sites-available
      - ./log-apache:/var/log/apache2
    networks:
      test_demo:
        ipv4_address: ${HTTPDIP}

  php-fpm:
    image: ${DUSER}/${FPM_IMAGE}:${UBUNTU_VERSION}.${PHP_VERSION}
    container_name: con-${FPM_IMAGE}
    environment:
      - TIMEZONE=${TIMEZONE}
      - OWN_USER=${OWN_USER}
      - OWN_GID=${OWN_GID}
      - OWN_UID=${OWN_UID}
      - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./www:/var/www
      - ./log-xdebug:/tmp/xdebug
      - ./log-fpm:/tmp/log-fpm
    networks:
      test_demo:
        ipv4_address: ${FPMIP}

networks:
  test_demo:
    driver: bridge
    name: test_demo
    ipam:
      config:
      -
        subnet: ${SUBNET}
